name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 21098 pixelcor@162.0.217.178 << 'EOF'
            source /home/pixelcor/nodevenv/public_html/github/trashtrek.pixelcore.lk/22/bin/activate && cd /home/pixelcor/public_html/github/trashtrek.pixelcore.lk
            npm install
            cloudlinux-selector stop--json --interpreter nodejs --user pixelcor --app-root /home/pixelcor/public_html/github/trashtrek.pixelcore.lk
            cloudlinux-selector start--json --interpreter nodejs --user pixelcor --app-root /home/pixelcor/public_html/github/trashtrek.pixelcore.lk
          EOF
